### ISSUE TITLE
🤖 [FEATURE] 프로젝트 추가 세팅

### ISSUE THREAD

**Issue by wjdtkdgns** [YAPP-Github/23rd-Android-Team-1-BE#1]
# 🤖 기능 개요

깃헙 템플릿 세팅 및 플러그인을 추가합니다

### ✅ Implement TODO

- [x] issue, pull request template
- [x] ktlint 적용
- [x] jacoco, sonaqube 적용

### 🚧 작업 브랜치

feature/issue-1/setting

**Comment by DongGeon0908** [comment]
https://springdoc.org/
boot3 + swagger3 도전해볼까 합니다. retry..

**Comment by wjdtkdgns** [comment]
> https://springdoc.org/ boot3 + swagger3 도전해볼까 합니다. retry..

헉 좋습니다~~
최대한 빨리 마무리 해볼게요 
소나큐브 남았어요!
